openapi: 3.1.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
paths:
  /posts:
    get:
      summary: Get all posts
      description: Returns a list of all posts.
      responses:
        '200':
          description: A list of posts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  /posts/{date}:
    get:
      summary: Get single post
      description: Returns a single post by its ID.
      parameters:
        - name: date
          in: path
          required: true
          description: Date of the post in YYYY-MM-DD format
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A single post.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
  /posts/dates:
    get:
      summary: Get dates of posts
      description: Returns a list of dates for which posts exist.
      responses:
        '200':
          description: A list of dates.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: date
components:
  schemas:
    Media:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
    Post:
      type: object
      properties:
        content:
          type: string
        date:
          type: string
        media:
          type: array
          items:
            $ref: '#/components/schemas/Media'